### ISSUE TITLE
Could you please update it to accept audioplayers ^4.0.1?

### ISSUE THREAD

**Issue by wann2** [mayurpitroda96/easy_audio_trimmer#3]
% flutter pub add easy_audio_trimmer
Because every version of easy_audio_trimmer depends on audioplayers ^1.1.1 and thor depends on audioplayers ^4.0.1, easy_audio_trimmer is forbidden.
So, because thor depends on easy_audio_trimmer any, version solving failed.

**Comment by triay0** [comment]
+1

**Comment by eugenz3rr** [comment]
+1

**Comment by eugenz3rr** [comment]
I created a fork that seams to work. You guys can check if you want.
The only thing I did was to apply updates.

Replace

```
  easy_audio_trimmer: xyz
```
with
```
  easy_audio_trimmer:
    git:
      url: https://github.com/eugenz3rr/easy_audio_trimmer.git
```

**Comment by anantmann9057** [comment]
@eugenz3rr thanks it was conflicting with ffmpeg and video trimmer before now all is working fine..

**Comment by mayurpitroda96** [comment]
fixed use latest version easy_audio_trimmer: ^1.0.2+4
