### ISSUE TITLE
Update package http: ^1.0.0 and above

### ISSUE THREAD

**Issue by Snehal4646** [mayurpitroda96/easy_audio_trimmer#5]
Please update page to support http: ^1.0.0 and above.

**Comment by eugenz3rr** [comment]
+1

**Comment by eugenz3rr** [comment]
I created a fork that seams to work. You guys can check if you want.
The only thing I did was to apply updates.

Replace

```
  easy_audio_trimmer: xyz
```
with
```
  easy_audio_trimmer:
    git:
      url: https://github.com/eugenz3rr/easy_audio_trimmer.git
```

**Comment by mayurpitroda96** [comment]
fixed use latest version easy_audio_trimmer: ^1.0.2+4
